site_description: "FIBOS 是一个结合 FIBJS 以及 EOS 的 JavaScript 的运行平台"
# google_analytics: UA-46852172-3
root_domain: dev.fo
# vue_version: 2.5.16

# platinum_sponsors_china:
#   - url: https://www.geekbang.org/
#     img: geekbang.png
#   - url: http://d3j.io/
#     img: coop5.png


special_sponsors:
  - url: https://code.xyz/
    img: codexyz.png
    description: Build APIs in Your Web Browser

platinum_sponsors:
  - url: https://www.bitsrc.io/?utm_source=vue&utm_medium=vue&utm_campaign=vue&utm_term=vue&utm_content=vue
    img: bit-wide.png
    alt_img: bit.png
  # - url: http://tooltwist.com/
  #   img: tooltwist.png
  #   name: tooltwist
